[data]
dir = "/asb-data/"

[network]
listen = ["/ip4/0.0.0.0/tcp/9839"]
external_addresses = []
rendezvous_point = [
   "/dns4/discover.unstoppableswap.net/tcp/8888/p2p/12D3KooWA6cnqJpVnreBVnoro8midDL9Lpzmg8oJPoAGi7YYaamE",
   "/dns4/discover2.unstoppableswap.net/tcp/8888/p2p/12D3KooWGRvf7qVQDrNR5nfYD6rKrbgeTi9x8RrbdxbmsPvxL4mw",
   "/dns4/darkness.su/tcp/8888/p2p/12D3KooWFQAgVVS9t9UgL6v1sLprJVM7am5hFK7vy9iBCCoCBYmU"
]

[bitcoin]
electrum_rpc_urls = ["tcp://testnet_electrs:60001"]
target_block = 1
network = "Testnet"

[monero]
daemon_url = "http://stagenet_monerod:38081"
network = "Stagenet"

[tor]
register_hidden_service = true
hidden_service_num_intro_points = 10

[maker]
min_buy_btc = 0.0004
max_buy_btc = 0.15
ask_spread = 0.00
price_ticker_ws_url = "wss://ws.kraken.com/"
